-- ============================================================
-- Migration 011: Reference Numbers
-- Introduces human-readable, structured reference numbers for
-- introducers and prospects/investors.
--
-- Format:
--   Introducer ref : XC-100  (3-digit, internal reserved 100–110)
--   Prospect ref   : XC-100-10001  (introducer prefix + 5-digit global seq)
--
-- Introducer ref assigned when agreement is signed.
-- Prospect ref auto-generated by DB trigger on INSERT.
-- ============================================================

-- ============================================================
-- 1. Sequences
-- ============================================================

-- External introducers start at 111 (100–110 reserved for internal/XC team)
CREATE SEQUENCE IF NOT EXISTS introducer_ref_seq
  START 111
  MINVALUE 111
  MAXVALUE 999
  NO CYCLE;

-- Global prospect sequence — starts at 10001 (always 5 digits)
CREATE SEQUENCE IF NOT EXISTS prospect_ref_seq
  START 10001
  MINVALUE 10001
  MAXVALUE 99999
  NO CYCLE;

-- ============================================================
-- 2. Schema additions
-- ============================================================

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS introducer_ref text UNIQUE;

ALTER TABLE public.prospects
  ADD COLUMN IF NOT EXISTS prospect_ref text UNIQUE;

-- ============================================================
-- 3. Pre-assign internal XC team refs (100, 101, 102)
--    Reserved range: XC-100 through XC-110
-- ============================================================

UPDATE public.profiles
  SET introducer_ref = 'XC-100'
  WHERE email = 'szymon.wloch@xenithcapital.co.uk'
    AND introducer_ref IS NULL;

UPDATE public.profiles
  SET introducer_ref = 'XC-101'
  WHERE email = 'rapten@xenithcapital.co.uk'
    AND introducer_ref IS NULL;

UPDATE public.profiles
  SET introducer_ref = 'XC-102'
  WHERE email = 'lukasz@xenithcapital.co.uk'
    AND introducer_ref IS NULL;

-- ============================================================
-- 4. Function: assign_introducer_ref
--    Called server-side (via RPC) when an introducer signs their
--    agreement. Idempotent — returns existing ref if already set.
-- ============================================================

CREATE OR REPLACE FUNCTION public.assign_introducer_ref(p_introducer_id uuid)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_existing text;
  v_seq_num  integer;
  v_new_ref  text;
BEGIN
  -- Return existing ref if already assigned (idempotent)
  SELECT introducer_ref
    INTO v_existing
    FROM public.profiles
   WHERE id = p_introducer_id;

  IF v_existing IS NOT NULL THEN
    RETURN v_existing;
  END IF;

  v_seq_num := nextval('introducer_ref_seq');
  v_new_ref := 'XC-' || LPAD(v_seq_num::text, 3, '0');

  UPDATE public.profiles
     SET introducer_ref = v_new_ref
   WHERE id = p_introducer_id;

  RETURN v_new_ref;
END;
$$;

-- ============================================================
-- 5. Function + trigger: auto-generate prospect_ref on INSERT
--    Format: <introducer_ref>-<5-digit global seq>
--    e.g.  XC-111-10001
-- ============================================================

CREATE OR REPLACE FUNCTION public.generate_prospect_ref()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_intro_ref  text;
  v_seq_num    bigint;
BEGIN
  -- Only generate if not already set (allows manual override in tests)
  IF NEW.prospect_ref IS NULL THEN
    SELECT introducer_ref
      INTO v_intro_ref
      FROM public.profiles
     WHERE id = NEW.introducer_id;

    IF v_intro_ref IS NULL THEN
      RAISE EXCEPTION
        'Cannot create prospect: introducer % has no reference number assigned. '
        'Ensure the introducer has completed onboarding before registering prospects.',
        NEW.introducer_id;
    END IF;

    v_seq_num := nextval('prospect_ref_seq');
    NEW.prospect_ref := v_intro_ref || '-' || LPAD(v_seq_num::text, 5, '0');
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER set_prospect_ref
  BEFORE INSERT ON public.prospects
  FOR EACH ROW
  EXECUTE FUNCTION public.generate_prospect_ref();

-- ============================================================
-- 6. Duplicate-detection index
--    Prevents two active prospects sharing the same email.
--    "Active" = anything that is not lost or rejected.
--    A prospect can be re-submitted after being closed out.
-- ============================================================

CREATE UNIQUE INDEX IF NOT EXISTS prospects_email_active_unique
  ON public.prospects (lower(email))
  WHERE status NOT IN ('lost', 'rejected');

-- ============================================================
-- 7. Indexes for fast ref lookups
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_profiles_introducer_ref
  ON public.profiles (introducer_ref)
  WHERE introducer_ref IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_prospects_prospect_ref
  ON public.prospects (prospect_ref)
  WHERE prospect_ref IS NOT NULL;
